name: Multipotentialisme
favicon: null
layout_spectrum: 0.5830876675900072
typography_spectrum: 0.8769271417986602
title: "Laisser la folie créative s'exprimer dans l'invention et l'innovation - lifehacking"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72369002-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.16937288618646562
  lightness: 0.18928313278593123
  saturation: 0.5783052151091397
  rhythmicContrast: 0.1979632629081607
purpose: []
