name: Multipotentialisme
favicon: null
layout_spectrum: 0.90786
typography_spectrum: 0.34003
title: "Laisser la folie créative s'exprimer dans l'invention et l'innovation - lifehacking"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72369002-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050503'
    - '#eef7fe'
    - '#5d5845'
    - '#938f72'
    - '#b5b4a0'
  brandStrength: 0.3125
  lightness: 0.18928313278593123
  saturation: 0.5783052151091397
  rhythmicContrast: 0.1979632629081607
purpose: []
